import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import LangMetaHandler from "./lang-meta-handler";
import { getTranslations } from "@/utils/translation/translate";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const translations = await getTranslations(params.lang);

  return (
        <div style={{
          "display": "flex",
          "flexDirection": "column",
          "height": "100vh"
        }}>
          <Navbar translations={translations.navbar} lang={params.lang}/>
          {children}
          <LangMetaHandler lang={params.lang}/>
        </div>
  );
}
