import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from '../lib/registry'
import GlobalStyles from "./styles/global-styles";
import Navbar from "@/components/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* TODO: make this only appear in the pages that use it (it doesn't seem to work with the Head component) */}
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin=""/>
      </head>
      <body className={inter.className}>
        <GlobalStyles/>
        <StyledComponentsRegistry>
          <div style={{
            "display": "flex",
            "flexDirection": "column",
            "height": "100vh"
          }}>
            <Navbar/>
            {children}
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
